create table Movie (
	id INT,
	name VARCHAR(50),
	releaseYear INT,
	genre VARCHAR(50),
	rating DECIMAL(2,1)
);
insert into Movie (id, name, releaseYear, genre, rating) values (1, 'All Is Forgiven (Tout est pardonné)', 1964, 'Drama', 2.4);
insert into Movie (id, name, releaseYear, genre, rating) values (2, 'Hardcore', 1984, 'Crime|Drama', 2.6);
insert into Movie (id, name, releaseYear, genre, rating) values (3, 'After Fall, Winter', 2012, 'Drama', 3.9);
insert into Movie (id, name, releaseYear, genre, rating) values (4, 'Camille Claudel', 1971, 'Drama', 4.6);
insert into Movie (id, name, releaseYear, genre, rating) values (5, 'Dans la peau d''une grande', 2014, 'Comedy', 1.0);
insert into Movie (id, name, releaseYear, genre, rating) values (6, 'Riley Rewind', 1996, 'Drama|Sci-Fi', 4.0);
insert into Movie (id, name, releaseYear, genre, rating) values (7, 'Lethal Weapon 4', 1969, 'Action|Comedy|Crime|Thriller', 4.8);
insert into Movie (id, name, releaseYear, genre, rating) values (8, 'Films to Keep You Awake: The Baby''s Room (Películas para no dormir: La habitación del niño)', 1995, 'Horror', 1.3);
insert into Movie (id, name, releaseYear, genre, rating) values (9, 'Anatomy of a Love Seen', 1988, 'Drama|Romance', 4.2);
insert into Movie (id, name, releaseYear, genre, rating) values (10, 'Hamlet', 1988, 'Drama', 3.4);
insert into Movie (id, name, releaseYear, genre, rating) values (11, 'Dumb and Dumber To', 2000, 'Comedy', 1.9);
insert into Movie (id, name, releaseYear, genre, rating) values (12, 'Generale Della Rovere, Il', 1959, 'Drama', 4.4);
insert into Movie (id, name, releaseYear, genre, rating) values (13, 'Article 99', 1975, 'Comedy|Drama', 3.3);
insert into Movie (id, name, releaseYear, genre, rating) values (14, 'On a Clear Day', 1962, 'Drama', 1.5);
insert into Movie (id, name, releaseYear, genre, rating) values (15, 'Bombay Talkie', 1964, 'Drama|Musical|Romance', 0.2);
insert into Movie (id, name, releaseYear, genre, rating) values (16, 'Hellraiser', 2001, 'Horror', 4.3);
insert into Movie (id, name, releaseYear, genre, rating) values (17, 'Man Who Copied, The (Homem Que Copiava, O)', 1951, 'Comedy|Crime|Drama|Romance', 3.8);
insert into Movie (id, name, releaseYear, genre, rating) values (18, 'I Was a Teenage Zombie', 2016, 'Comedy|Horror', 0.4);
insert into Movie (id, name, releaseYear, genre, rating) values (19, 'Private Property (Nue propriété)', 1988, 'Drama', 4.5);
insert into Movie (id, name, releaseYear, genre, rating) values (20, 'Notre jour viendra', 2003, 'Drama', 3.5);
insert into Movie (id, name, releaseYear, genre, rating) values (21, 'Brokeback Mountain', 1984, 'Drama|Romance', 3.5);
insert into Movie (id, name, releaseYear, genre, rating) values (22, 'Change of Plans (Le code a changé)', 1971, 'Comedy|Drama', 0.4);
insert into Movie (id, name, releaseYear, genre, rating) values (23, 'New Waterford Girl', 2002, 'Comedy', 4.0);
insert into Movie (id, name, releaseYear, genre, rating) values (24, 'Las Vegas Story, The', 2019, 'Crime|Drama|Film-Noir', 3.8);
insert into Movie (id, name, releaseYear, genre, rating) values (25, 'Becoming Chaz', 1962, 'Documentary', 0.1);
insert into Movie (id, name, releaseYear, genre, rating) values (26, 'Night Across the Street (La noche de enfrente)', 1953, 'Drama', 3.8);
insert into Movie (id, name, releaseYear, genre, rating) values (27, 'Loch Ness', 1951, 'Drama', 0.7);
insert into Movie (id, name, releaseYear, genre, rating) values (28, 'Beau Pere (a.k.a. Stepfather) (Beau-père)', 1996, 'Drama', 0.3);
insert into Movie (id, name, releaseYear, genre, rating) values (29, 'Milk of Sorrow, The (Teta asustada, La)', 1956, 'Drama', 0.2);
insert into Movie (id, name, releaseYear, genre, rating) values (30, 'Michael', 2009, 'Comedy|Drama|Fantasy|Romance', 2.7);
insert into Movie (id, name, releaseYear, genre, rating) values (31, 'Vai~E~Vem', 1996, 'Comedy|Drama', 3.2);
insert into Movie (id, name, releaseYear, genre, rating) values (32, 'Trial and Error', 1972, 'Comedy|Romance', 4.4);
insert into Movie (id, name, releaseYear, genre, rating) values (33, 'Octane', 1981, 'Horror|Thriller', 0.1);
insert into Movie (id, name, releaseYear, genre, rating) values (34, 'Captain America: The First Avenger', 1957, 'Action|Adventure|Sci-Fi|Thriller|War', 2.7);
insert into Movie (id, name, releaseYear, genre, rating) values (35, 'Wish Upon a Star', 1965, 'Comedy', 0.4);
insert into Movie (id, name, releaseYear, genre, rating) values (36, 'Medea', 2004, 'Drama', 1.8);
insert into Movie (id, name, releaseYear, genre, rating) values (37, 'White Night (Hvid nat)', 1985, 'Drama', 1.4);
insert into Movie (id, name, releaseYear, genre, rating) values (38, 'Rude Boy', 1979, 'Documentary|Drama', 1.8);
insert into Movie (id, name, releaseYear, genre, rating) values (39, 'Who Can Kill a Child? (a.k.a. Island of the Damned) (¿Quién puede matar a un niño?)', 1953, 'Horror|Mystery|Thriller', 3.5);
insert into Movie (id, name, releaseYear, genre, rating) values (40, 'Chaos', 1993, 'Action|Crime|Drama|Thriller', 0.7);
insert into Movie (id, name, releaseYear, genre, rating) values (41, 'I Am Jesus', 1980, 'Documentary', 0.4);
insert into Movie (id, name, releaseYear, genre, rating) values (42, 'Whistleblower, The', 1987, 'Drama|Thriller', 1.9);
insert into Movie (id, name, releaseYear, genre, rating) values (43, 'Song Is Born, A', 1968, 'Comedy|Musical', 1.1);
insert into Movie (id, name, releaseYear, genre, rating) values (44, 'Edward Scissorhands', 1984, 'Drama|Fantasy|Romance', 2.8);
insert into Movie (id, name, releaseYear, genre, rating) values (45, 'La Legge Violenta Della Squadra Anticrimine', 1984, 'Crime', 2.8);
insert into Movie (id, name, releaseYear, genre, rating) values (46, 'Behind Enemy Lines', 2005, 'Action|Thriller', 2.7);
insert into Movie (id, name, releaseYear, genre, rating) values (47, 'Hellsinki (Rööperi)', 1982, 'Crime', 1.7);
insert into Movie (id, name, releaseYear, genre, rating) values (48, 'Ulee''s Gold', 1970, 'Drama', 2.9);
insert into Movie (id, name, releaseYear, genre, rating) values (49, 'Hoodwinked Too! Hood vs. Evil', 1983, 'Animation|Comedy', 4.2);
insert into Movie (id, name, releaseYear, genre, rating) values (50, 'Silent Witness (Do Not Disturb)', 1978, 'Action|Comedy|Thriller', 4.2);
insert into Movie (id, name, releaseYear, genre, rating) values (51, 'Patrick', 1975, 'Horror|Sci-Fi|Thriller', 4.2);
insert into Movie (id, name, releaseYear, genre, rating) values (52, 'Accused, The', 2014, 'Drama', 1.8);
insert into Movie (id, name, releaseYear, genre, rating) values (53, 'Playing for Keeps', 1975, 'Comedy|Romance', 1.0);
insert into Movie (id, name, releaseYear, genre, rating) values (54, 'Last Truck: Closing of a GM Plant, The', 1977, 'Documentary', 3.6);
insert into Movie (id, name, releaseYear, genre, rating) values (55, 'Golden Compass, The', 2011, 'Adventure|Children|Fantasy', 2.2);
insert into Movie (id, name, releaseYear, genre, rating) values (56, 'Exodus', 2004, 'Drama|Romance|War', 4.5);
insert into Movie (id, name, releaseYear, genre, rating) values (57, 'A Grain of Truth', 1989, 'Thriller', 2.8);
insert into Movie (id, name, releaseYear, genre, rating) values (58, 'Incendiary', 1978, 'Drama|Mystery|Romance|Thriller', 0.3);
insert into Movie (id, name, releaseYear, genre, rating) values (59, 'Omega Code, The', 1988, 'Action', 2.6);
insert into Movie (id, name, releaseYear, genre, rating) values (60, 'AKA', 1964, 'Drama', 3.8);
insert into Movie (id, name, releaseYear, genre, rating) values (61, 'Lumberjacking (Nuoruuteni savotat)', 1972, 'Drama', 1.6);
insert into Movie (id, name, releaseYear, genre, rating) values (62, 'Luxo Jr.', 1969, 'Animation|Children', 0.3);
insert into Movie (id, name, releaseYear, genre, rating) values (63, 'Garden State', 2003, 'Comedy|Drama|Romance', 2.0);
insert into Movie (id, name, releaseYear, genre, rating) values (64, 'Martín (Hache)', 2004, 'Drama', 0.9);
insert into Movie (id, name, releaseYear, genre, rating) values (65, 'Nicholas Nickleby', 1953, 'Drama|Romance', 0.9);
insert into Movie (id, name, releaseYear, genre, rating) values (66, 'War of the Robots (La guerra dei robot)', 1978, 'Action|Adventure|Sci-Fi', 1.5);
insert into Movie (id, name, releaseYear, genre, rating) values (67, 'Premature', 2003, 'Comedy', 3.5);
insert into Movie (id, name, releaseYear, genre, rating) values (68, 'Islands in the Stream', 1973, 'Drama', 1.9);
insert into Movie (id, name, releaseYear, genre, rating) values (69, 'Coming to America', 1985, 'Comedy|Romance', 1.3);
insert into Movie (id, name, releaseYear, genre, rating) values (70, 'To Be Twenty', 1978, 'Comedy|Drama|Horror', 3.1);
insert into Movie (id, name, releaseYear, genre, rating) values (71, 'Wall Street', 1989, 'Drama', 5.0);
insert into Movie (id, name, releaseYear, genre, rating) values (72, 'Last Rites of Joe May, The', 1966, 'Drama', 2.9);
insert into Movie (id, name, releaseYear, genre, rating) values (73, 'Kevin Hart: Seriously Funny', 1958, 'Comedy', 4.5);
insert into Movie (id, name, releaseYear, genre, rating) values (74, 'Night and the City', 1957, 'Film-Noir|Thriller', 5.0);
insert into Movie (id, name, releaseYear, genre, rating) values (75, 'Agent Cody Banks 2: Destination London', 2012, 'Action|Adventure|Children|Comedy', 1.1);
insert into Movie (id, name, releaseYear, genre, rating) values (76, 'Manhunt', 2005, 'Horror|Thriller', 1.6);
insert into Movie (id, name, releaseYear, genre, rating) values (77, 'Chronicles of Narnia: The Voyage of the Dawn Treader, The', 1950, 'Adventure|Children|Fantasy', 4.9);
insert into Movie (id, name, releaseYear, genre, rating) values (78, 'Die Another Day', 1970, 'Action|Adventure|Thriller', 0.4);
insert into Movie (id, name, releaseYear, genre, rating) values (79, 'Queen of Blood', 1973, 'Horror|Sci-Fi', 1.7);
insert into Movie (id, name, releaseYear, genre, rating) values (80, 'Child I Never Was, The (Leben lang kurze Hosen Tragen, Ein)', 2000, 'Crime|Drama', 3.6);
insert into Movie (id, name, releaseYear, genre, rating) values (81, 'Papusza', 2007, 'Drama', 3.1);
insert into Movie (id, name, releaseYear, genre, rating) values (82, 'Doom', 1998, 'Action|Horror|Sci-Fi', 2.7);
insert into Movie (id, name, releaseYear, genre, rating) values (83, 'Bella', 1978, 'Drama|Romance', 2.9);
insert into Movie (id, name, releaseYear, genre, rating) values (84, 'Foon', 2001, 'Comedy', 3.2);
insert into Movie (id, name, releaseYear, genre, rating) values (85, 'Casting By', 2017, 'Documentary', 4.4);
insert into Movie (id, name, releaseYear, genre, rating) values (86, 'Roaring Twenties, The', 1996, 'Crime|Drama|Thriller', 1.0);
insert into Movie (id, name, releaseYear, genre, rating) values (87, 'I, Robot', 1976, 'Action|Adventure|Sci-Fi|Thriller', 3.1);
insert into Movie (id, name, releaseYear, genre, rating) values (88, 'Naked Face, The', 2008, 'Action|Mystery|Thriller', 2.6);
insert into Movie (id, name, releaseYear, genre, rating) values (89, 'Resident Evil: Afterlife', 1953, 'Action|Horror|Sci-Fi|Thriller|IMAX', 4.9);
insert into Movie (id, name, releaseYear, genre, rating) values (90, 'Arsène Lupin Returns', 1975, 'Mystery', 4.5);
insert into Movie (id, name, releaseYear, genre, rating) values (91, 'Millionaire for Christy, A (Golden Goose) (No Room for the Groom)', 2007, 'Comedy|Romance', 4.8);
insert into Movie (id, name, releaseYear, genre, rating) values (92, 'Buffalo Soldiers', 2008, 'Comedy|Crime|Drama|War', 4.0);
insert into Movie (id, name, releaseYear, genre, rating) values (93, 'Onechanbara - Zombie Bikini Squad (a.k.a. Oneechanbara: The Movie)', 1991, 'Action|Horror', 1.0);
insert into Movie (id, name, releaseYear, genre, rating) values (94, 'Wishful Thinking', 1991, 'Comedy', 4.0);
insert into Movie (id, name, releaseYear, genre, rating) values (95, 'Reefer Madness (a.k.a. Tell Your Children)', 2019, 'Comedy|Drama', 2.3);
insert into Movie (id, name, releaseYear, genre, rating) values (96, 'Last Time I Saw Archie, The', 1981, 'Comedy|Romance|War', 4.5);
insert into Movie (id, name, releaseYear, genre, rating) values (97, 'Rocks (Rad, Das)', 1953, 'Action|Animation|Fantasy', 0.4);
insert into Movie (id, name, releaseYear, genre, rating) values (98, 'Samaritan Girl (Samaria)', 2019, 'Drama', 2.8);
insert into Movie (id, name, releaseYear, genre, rating) values (99, 'Muppets Most Wanted', 1980, 'Adventure|Comedy|Crime', 4.0);
insert into Movie (id, name, releaseYear, genre, rating) values (100, 'Things Behind the Sun', 1992, 'Drama', 2.0);
